### ISSUE TITLE
Dependencies packages are not part of the environment

### ISSUE THREAD

**Issue by SirLynix** [xmake-io/xmake#1371]
### Describe the bug
On Windows, when making a simple binary target depending on a package (SDL for example), running it (either using xmake run or vsxmake) works, without needing to put SDL2.dll next to the .exe

For example, this works:
```lua
add_rules("mode.debug", "mode.release")
add_requires("libsdl")

target("test_sdl")
    set_kind("binary")
    add_files("src/*.cpp")
    add_packages("libsdl")
```

However, if this dependency comes from a static or shared library linked to the binary target, xmake run (or running from vsxmake) doesn't set take libsdl package in the environment.

```lua
add_rules("mode.debug", "mode.release")
add_requires("libsdl")

target("test_lib")
    set_kind("shared")
    add_files("src/lib.cpp")
    add_packages("libsdl")
    add_defines("BUILDING")

target("test_main")
    add_deps("test_lib")
    set_kind("binary")
    add_files("src/main.cpp")
```

```
$ xmake.exe run test_main
error: execv(C:\Projets\Tests\xmake-build\test_sdl2\build\windows\x64\debug\test_main.exe) failed(-1073741515)
```

With the following missing DLL error:
![image](https://user-images.githubusercontent.com/3002461/116394081-c147e180-a822-11eb-96a7-93d9d31f7592.png)

### Expected behavior
That the package environments required to run the binary gets inherited when using `add_deps` to a static or shared library.

For a static library, I suppose adding the package with `{public = true}` would fix this, but not for a shared one.

### Related Environment

Please provide compiling and running environment information:

- xmake version: xmake dev 
- os: Windows 10
- target platform: Windows 10

### Additional context

Here are the files used to run the test (I know this isn't really the best way to use SDL, it's just for testing):

**xmake.lua**
```lua
add_rules("mode.debug", "mode.release")
add_requires("libsdl")

target("test_lib")
    set_kind("shared")
    add_files("src/lib.cpp")
    add_packages("libsdl")
    add_defines("BUILDING")

target("test_main")
    add_deps("test_lib")
    set_kind("binary")
    add_files("src/main.cpp")
```

**src/lib.hpp**:
```cpp
#pragma once

#ifdef BUILDING
#define API __declspec(dllexport)
#else
#define API __declspec(dllimport)
#endif

API void helloworld();
```

**src/lib.cpp**:
```cpp
#include "lib.hpp"
#define SDL_MAIN_HANDLED
#include <SDL.h>
#include <iostream>

void helloworld()
{
    if (SDL_Init(0) != 0)
    {
        std::cout << "failed to initialize SDL" << std::endl;
        return;
    }

    std::cout << "hello world!" << std::endl;

    SDL_Quit();
}
```

**src/main.cpp**:
```cpp
#include "lib.hpp"

int main()
{
    helloworld();
}
```

**Comment by waruqi** [comment]
I have fixed it, only xmake-repo/libsdl issue. you can run `xmake repo -u` to update libsdl package and reinstall libsdl.

```console
xmake repo -u
xrepo remove libsdl
xmake f -c -vD
xmake 
xmake run
```

**Comment by SirLynix** [comment]
Thanks, but I had the same problem with freetype 😅

**Comment by SirLynix** [comment]
I can confirm it works using `xmake run` (even with freetype), thanks for that. However I still have the missing DLL error when trying to run test_sdl from Visual Studio (using a vsxmake project).

**Comment by waruqi** [comment]
I have fixed it.

**Comment by SirLynix** [comment]
Can confirm it works great! Thank you.
