### ISSUE TITLE
No colors in powershell

### ISSUE THREAD

**Issue by WubiCookie** [xmake-io/xmake#1501]
### Describe the bug
Colors in powershell are not displayed as colors, the escape character is not interpreted correctly.
It can be reproduced by forcing a git repository cloning from a package.
`add_requires("stb")` in xmake.lua and `xmake q -yf stb` in powershell.

### Expected behavior
Colors should always be displayed as colors.

### Error output
```
> xmake q -yf stb
←[0m←[38;5;3m  => ←[0mclone https://github.com/nothings/stb.git 0.0 .. ←[38;5;2;1mok←[0m8←[1K[1K
←[0m←[38;5;3m  => ←[0minstall stb 0.0 .. ←[38;5;2;1mok←[0mm .. ←[2m(1/cl.exe)←[0m ←[0m←7⠦←8←[1K
```

### Related Environment

- xmake version: xmake v2.5.5+202107060308
- os: Windows 10 x64
- powershell: v7.2.0-preview.7 ( https://github.com/PowerShell/PowerShell/releases/tag/v7.2.0-preview.7 )

**Comment by waruqi** [comment]
I have fixed it. 

This is a problem caused by the `git submodule update --init` command. If you remove it, the color code will not be broken.

https://github.com/xmake-io/xmake/commit/0d01a974ac4ffcf85f6349dc899c4b83635a951e

But this is just a workaround solution. If you want to download a git project with submodules, there will still be this problem.

But at least it will be much better than it is now.

**Comment by SirLynix** [comment]
Maybe git causes a change in powershell mode (or whatever) that sticks after execution?
One way to fix this would be to know what changes and reset it, or maybe run git in a background process (with popen) and replicate its stdout to the shell?

**Comment by waruqi** [comment]
> Maybe git causes a change in powershell mode (or whatever) that sticks after execution?
> One way to fix this would be to know what changes and reset it, or maybe run git in a background process (with popen) and replicate its stdout to the shell?

I don't know what it has changed, but I can only reduce to run it.

**Comment by waruqi** [comment]
maybe git submodule will change this.

https://github.com/xmake-io/xmake/blob/4d62362c12ec2c3dbf387cbee561574c051d4bcf/core/src/xmake/engine.c#L916

**Comment by WubiCookie** [comment]
ShaderWriter is based on submodules and they are not pulled anymore 😢 
Maybe beacause `.gitmodules` is a file and not a folder?
https://github.com/xmake-io/xmake/commit/0d01a974ac4ffcf85f6349dc899c4b83635a951e#diff-47fadb4eb8d3f931476b37842bccf43435aebd1287e7c161adecfcd9ed78b5faR86

**Comment by waruqi** [comment]
I have fixed it, try it again.

xmake update -s github:xmake-io/xmake#dev

**Comment by WubiCookie** [comment]
Still no luck... xmake seems to check if the .gitmodule exists in `AppData\Local\.xmake\cache\packages\2107\s\shaderwriter1\1.0.1`
but the file is actually in `AppData\Local\.xmake\cache\packages\2107\s\shaderwriter1\1.0.1\source\shaderwriter1`

**Comment by waruqi** [comment]
> Still no luck... xmake seems to check if the .gitmodules file exists in
> `AppData\Local\.xmake\cache\packages\2107\s\shaderwriter1\1.0.1`
> but the file is actually in
> `AppData\Local\.xmake\cache\packages\2107\s\shaderwriter1\1.0.1\source\shaderwriter1`

I have fixed it, try it again.

**Comment by WubiCookie** [comment]
It works now, thank you very much!
