### ISSUE TITLE
"vcpkg::zlib 1.2.11+10" doesn't exist and "vcpkg::zlib 1.2.11#10" doesn't work

### ISSUE THREAD

**Issue by richard-sim** [xmake-io/xmake#5660]
### Xmake Version

2.9.5

### Operating System Version and Architecture

Windows 11

### Describe Bug

From the docs:
```lua
add_requires("vcpkg::zlib 1.2.11+10")
```

Results in:
```console
error: no version database entry for zlib at 1.2.11+10.
Available versions:
  ...
  1.2.11#10
 ```

Trying:
```lua
add_requires("vcpkg::zlib 1.2.11#10")
```

Will find and install the package in vcpkg, but xmake will fail when parsing the semver with the `#` in it.

### Expected Behavior

vcpkg::zlib should be able to be installed as 1.2.11#10.

### Project Configuration

```lua
add_requires("vcpkg::zlib 1.2.11#10", {alias = "zlib"})

target("deps", function ()
    set_kind("phony")
    add_packages("zlib")
end)
```

### Additional Information and Error Logs

```console
(dev) D:\dev\build-sys-eval\foobar\src>tools\xmake\xmake.exe -v deps
checking for platform ... windows
checking for architecture ... x64
checking for cl.exe ... C:\Program Files\Microsoft Visual Studio\2022\Preview\VC\Tools\MSVC\14.42.34321\bin\HostX64\x64\cl.exe
checking for Microsoft Visual Studio (x64) version ... 2022
checking for Microsoft C/C++ Compiler (x64) version ... 19.42.34321.1
checking for zig ... no
checking for zig ... no
checking for nim ... no
checking for nim ... no
checking for git ... ok
checking for gzip ... no
checking for 7z ... D:\dev\build-sys-eval\foobar\src\tools\xmake\winenv\bin\7z
checking for vcpkg::zlib ... no
note: install or modify (m) these packages (pass -y to skip confirm)?
in vcpkg:
  -> vcpkg::zlib 1.2.11#10 [runtimes:"MT"]
please input: y (y/n/m)

checking for vcpkg.exe ... C:\Program Files\Microsoft Visual Studio\2022\Preview\VC\vcpkg\vcpkg.exe
C:\Program Files\Microsoft Visual Studio\2022\Preview\VC\vcpkg\vcpkg.exe --feature-flags=\"versions\" install --x-wait-for-lock --triplet x64-windows-static
Fetching registry information from https://github.com/microsoft/vcpkg (HEAD)...
Detecting compiler hash for triplet x64-windows-static...
Compiler found: C:/Program Files/Microsoft Visual Studio/2022/Preview/VC/Tools/MSVC/14.42.34321/bin/Hostx64/x64/cl.exe
The following packages will be built and installed:
    zlib:x64-windows-static@1.2.11#10 -- C:\Users\rsim\AppData\Local\vcpkg\registries\git-trees\53a4615c8bb9b98a3864b834a6bbe51cc6c849ef
Restored 1 package(s) from C:\Users\rsim\AppData\Local\vcpkg\archives in 43 ms. Use --debug to see more details.
Installing 1/1 zlib:x64-windows-static@1.2.11#10...
Elapsed time to handle zlib:x64-windows-static: 2.07 ms
zlib:x64-windows-static package ABI: 16ce7548cbfefdd017172ca8248d2af48c1785ad68e4f21b2a85abb9475bde74
Total install time: 2.17 ms
The package zlib is compatible with built-in CMake targets:

    find_package(ZLIB REQUIRED)
    target_link_libraries(main PRIVATE ZLIB::ZLIB)

checking for pkg-config ... no
checking for pkgconf ... no
error: unable to parse semver range '1.2.11#10'
  => install vcpkg::zlib 1.2.11#10 .. failed
error: install failed!
```

**Comment by waruqi** [comment]
Why not use `add_requires("zlib 1.2.11")`?

**Comment by waruqi** [comment]
> I'm trying to follow the docs exactly. :) I don't know the difference between the versions in VCPkg, and since the docs specified +10, I assumed it was important for some reason.

where? it's incorrect, it should be `add_requires("vcpkg::zlib 1.2.11")`

**Comment by richard-sim** [comment]
https://xmake.io/#/package/remote_package?id=add-vcpkg-dependency-package

Under:
> After v2.6.3, xmake supports the new manifest mode of vcpkg, through which we can support version selection of vcpkg package, for example:

**Comment by waruqi** [comment]
I have updated docs.

**Comment by richard-sim** [comment]
Thanks!

however, `"vcpkg::zlib 1.2.11"` still doesn't work, but for a completely different reason it seems.

```console
-- Configuring x64-windows-static
CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:127 (message):
    Command failed: "C:/Program Files/Microsoft Visual Studio/2022/Preview/Common7/IDE/CommonExtensions/Microsoft/CMake/Ninja/ninja.exe" -v
    Working Directory: D:/dev/build-sys-eval/foobar/src/build/.packages/v/vcpkg_zlib/1.2.11/069a57d9b1244d018305965146a59983/vcpkg_installed/vcpkg/blds/zlib/x64-windows-static-rel/vcpkg-parallel-configure
    Error code: 1
    See logs for more information:
      D:\dev\build-sys-eval\foobar\src\build\.packages\v\vcpkg_zlib\1.2.11\069a57d9b1244d018305965146a59983\vcpkg_installed\vcpkg\blds\zlib\config-x64-windows-static-dbg-CMakeCache.txt.log
      D:\dev\build-sys-eval\foobar\src\build\.packages\v\vcpkg_zlib\1.2.11\069a57d9b1244d018305965146a59983\vcpkg_installed\vcpkg\blds\zlib\config-x64-windows-static-rel-CMakeCache.txt.log
      D:\dev\build-sys-eval\foobar\src\build\.packages\v\vcpkg_zlib\1.2.11\069a57d9b1244d018305965146a59983\vcpkg_installed\vcpkg\blds\zlib\config-x64-windows-static-out.log

Call Stack (most recent call first):
  scripts/cmake/vcpkg_configure_cmake.cmake:314 (vcpkg_execute_required_process)
  C:/Users/rsim/AppData/Local/vcpkg/registries/git-trees/356c8b9d736b19e30f83d7ef735d21e0c063c6ca/portfile.cmake:10 (vcpkg_configure_cmake)
  scripts/ports.cmake:192 (include)
```

From `config-x64-windows-static-out.log`:
```console
-- Check for working C compiler: C:/Program Files/Microsoft Visual Studio/2022/Preview/VC/Tools/MSVC/14.42.34321/bin/Hostx64/x64/cl.exe - broken
CMake Error at C:/Program Files/Microsoft Visual Studio/2022/Preview/Common7/IDE/CommonExtensions/Microsoft/CMake/CMake/share/cmake-3.29/Modules/CMakeTestCCompiler.cmake:67 (message):
  The C compiler

    "C:/Program Files/Microsoft Visual Studio/2022/Preview/VC/Tools/MSVC/14.42.34321/bin/Hostx64/x64/cl.exe"

  is not able to compile a simple test program.

  It fails with the following output:

    Change Dir: 'D:/dev/build-sys-eval/foobar/src/build/.packages/v/vcpkg_zlib/1.2.11/069a57d9b1244d018305965146a59983/vcpkg_installed/vcpkg/blds/zlib/x64-windows-static-rel/CMakeFiles/CMakeScratch/TryCompile-ntagsl'
    
    Run Build Command(s): "C:/Program Files/Microsoft Visual Studio/2022/Preview/MSBuild/Current/Bin/amd64/MSBuild.exe" cmTC_c2fb8.vcxproj /p:Configuration=Debug /p:Platform=x64 /p:VisualStudioVersion=17.0 /v:n
    MSBuild version 17.12.0-preview-24426-07+07a6d0d9c for .NET Framework
    Build started 25/09/2024 7:29:13 AM.
    
    Project "D:\dev\build-sys-eval\foobar\src\build\.packages\v\vcpkg_zlib\1.2.11\069a57d9b1244d018305965146a59983\vcpkg_installed\vcpkg\blds\zlib\x64-windows-static-rel\CMakeFiles\CMakeScratch\TryCompile-ntagsl\cmTC_c2fb8.vcxproj" on node 1 (default targets).
    PrepareForBuild:
      Creating directory "cmTC_c2fb8.dir\Debug\".
      Structured output is enabled. The formatting of compiler diagnostics will reflect the error hierarchy. See https://aka.ms/cpp/structured-output for more details.
      Creating directory "D:\dev\build-sys-eval\foobar\src\build\.packages\v\vcpkg_zlib\1.2.11\069a57d9b1244d018305965146a59983\vcpkg_installed\vcpkg\blds\zlib\x64-windows-static-rel\CMakeFiles\CMakeScratch\TryCompile-ntagsl\Debug\".
      Creating directory "cmTC_c2fb8.dir\Debug\cmTC_c2fb8.tlog\".
    InitializeBuildStatus:
      Creating "cmTC_c2fb8.dir\Debug\cmTC_c2fb8.tlog\unsuccessfulbuild" because "AlwaysCreate" was specified.
      Touching "cmTC_c2fb8.dir\Debug\cmTC_c2fb8.tlog\unsuccessfulbuild".
    ClCompile:
      C:\Program Files\Microsoft Visual Studio\2022\Preview\VC\Tools\MSVC\14.42.34321\bin\HostX64\x64\CL.exe /c /Z7 /nologo /W1 /WX- /diagnostics:column /MP /Od /Ob0 /D _MBCS /D WIN32 /D _WINDOWS /D _DEBUG /D "CMAKE_INTDIR=\"Debug\"" /Gm- /RTC1 /MTd /GS /fp:precise /Zc:wchar_t /Zc:forScope /Zc:inline /Fo"cmTC_c2fb8.dir\Debug\\" /Fd"cmTC_c2fb8.dir\Debug\vc143.pdb" /external:W1 /Gd /TC /errorReport:queue  /utf-8 "D:\dev\build-sys-eval\foobar\src\build\.packages\v\vcpkg_zlib\1.2.11\069a57d9b1244d018305965146a59983\vcpkg_installed\vcpkg\blds\zlib\x64-windows-static-rel\CMakeFiles\CMakeScratch\TryCompile-ntagsl\testCCompiler.c"
      testCCompiler.c
    Link:
      C:\Program Files\Microsoft Visual Studio\2022\Preview\VC\Tools\MSVC\14.42.34321\bin\HostX64\x64\link.exe /ERRORREPORT:QUEUE /OUT:"D:\dev\build-sys-eval\foobar\src\build\.packages\v\vcpkg_zlib\1.2.11\069a57d9b1244d018305965146a59983\vcpkg_installed\vcpkg\blds\zlib\x64-windows-static-rel\CMakeFiles\CMakeScratch\TryCompile-ntagsl\Debug\cmTC_c2fb8.exe" /INCREMENTAL /ILK:"cmTC_c2fb8.dir\Debug\cmTC_c2fb8.ilk" /NOLOGO kernel32.lib user32.lib gdi32.lib winspool.lib shell32.lib ole32.lib oleaut32.lib uuid.lib comdlg32.lib advapi32.lib /MANIFEST /MANIFESTUAC:"level='asInvoker' uiAccess='false'" /manifest:embed /DEBUG /PDB:"D:/dev/build-sys-eval/foobar/src/build/.packages/v/vcpkg_zlib/1.2.11/069a57d9b1244d018305965146a59983/vcpkg_installed/vcpkg/blds/zlib/x64-windows-static-rel/CMakeFiles/CMakeScratch/TryCompile-ntagsl/Debug/cmTC_c2fb8.pdb" /SUBSYSTEM:CONSOLE /TLBID:1 /DYNAMICBASE /NXCOMPAT /IMPLIB:"D:/dev/build-sys-eval/foobar/src/build/.packages/v/vcpkg_zlib/1.2.11/069a57d9b1244d018305965146a59983/vcpkg_installed/vcpkg/blds/zlib/x64-windows-static-rel/CMakeFiles/CMakeScratch/TryCompile-ntagsl/Debug/cmTC_c2fb8.lib" /MACHINE:X64  /machine:x64 /nologo cmTC_c2fb8.dir\Debug\testCCompiler.obj
    FileTracker : error FTK1011: could not create the new file tracking log file: D:\dev\build-sys-eval\foobar\src\build\.packages\v\vcpkg_zlib\1.2.11\069a57d9b1244d018305965146a59983\vcpkg_installed\vcpkg\blds\zlib\x64-windows-static-rel\CMakeFiles\CMakeScratch\TryCompile-ntagsl\cmTC_c2fb8.dir\Debug\cmTC_c2fb8.tlog\link-cvtres.write.1.tlog. The system cannot find the path specified. [D:\dev\build-sys-eval\foobar\src\build\.packages\v\vcpkg_zlib\1.2.11\069a57d9b1244d018305965146a59983\vcpkg_installed\vcpkg\blds\zlib\x64-windows-static-rel\CMakeFiles\CMakeScratch\TryCompile-ntagsl\cmTC_c2fb8.vcxproj]
```

It looks like the issue is with the very long path of the log file:
`D:\dev\build-sys-eval\foobar\src\build\.packages\v\vcpkg_zlib\1.2.11\069a57d9b1244d018305965146a59983\vcpkg_installed\vcpkg\blds\zlib\x64-windows-static-rel\CMakeFiles\CMakeScratch\TryCompile-ntagsl\cmTC_c2fb8.dir\Debug\cmTC_c2fb8.tlog\link-cvtres.write.1.tlog`

That path is 260 characters, which is MAX_PATH on Windows. I've got Windows 11 configured to support long paths, but that's only as good as the compatibility of the tools, and it appears that the MSVC `link.exe` and `cl.exe` don't support long paths(!!!).

See these bug reports for MSVC:
https://developercommunity.visualstudio.com/t/linkexe-fails-to-open-a-file-exceeding/10526011?space=41&sort=newest
https://developercommunity.visualstudio.com/t/clexe-compiler-driver-cannot-handle-long-file-path/975889

uhh... so. I'm not sure what to do there. Obviously we have no control over MSVC's long-path behaviour, and since those bugs are quite old, it doesn't appear the MSVC team are very interested in fixing their end.

My project path isn't unreasonably long, but it's certainly not overly-short either. I specifically chose it for this test project as it's a realistic example of path hierarchies in a large project. Perhaps xmake could support relocating the hard-coded `./build/.packages/` folder it uses, so I can put it somewhere like `D:\xmake.p\`? It wouldn't get around deeply nested projects, but I don't think there's a better option at this time.

**Comment by waruqi** [comment]
it's vcpkg issue, not xmake. vcpkg need to support long path for cl.exe.

or you can modify registry to enable long path support for windows.
