### ISSUE TITLE
Can't import std with GCC15.1

### ISSUE THREAD

**Issue by DawnMagnet** [xmake-io/xmake#6384]
### Xmake 版本

xmake v2.9.9+20250408

### 操作系统版本和架构

Archlinux Linux 6.14.4-2-cachyos #1 SMP PREEMPT_DYNAMIC Fri, 25 Apr 2025 16:33:29 +0000 x86_64 GNU/Linux

### 描述问题

Can't import std with xmake 

```cpp
import std;

int main() {
  std::cout << std::format("Hello world! {}", 2024) << std::endl;

  return 0;
}
```

### 期待的结果

compile success

### 工程配置

```xmake
set_languages("c++latest")
target("main")
    set_kind("binary")
    add_files("main.cpp")
```

### 附加信息和错误日志

```console
checking for platform ... linux
checking for architecture ... x86_64
checking for gcc ... /usr/bin/gcc
mcheckinfo: cannot runv(nim --version), No such file or directory
checking for nim ... no
mcheckinfo: cannot runv(nim --version), No such file or directory
checking for nim ... no
checking for gcc ... /usr/bin/gcc
checking for the c++ compiler (cxx) ... gcc
checking for /usr/bin/gcc ... ok
checking for flags (-fPIC) ... ok
> gcc "-fPIC" "-m64"
checking for flags (-std=c++26) ... ok
> gcc "-std=c++26" "-m64"
[ 50%]: cache compiling.release main.cpp
/usr/bin/gcc -c -m64 -std=c++26 -Ibuild/.gens/main/linux/x86_64/release/platform/windows/idl -o build/.objs/main/linux/x86_64/release/main.cpp.o main.cpp
checking for flags (-MMD -MF) ... ok
> gcc "-MMD" "-MF" "/dev/null" "-m64"
checking for flags (-Wno-gnu-line-marker -Werror) ... ok
> gcc "-Wno-gnu-line-marker" "-Werror" "-m64"
error: @programdir/core/main.lua:329: @programdir/actions/build/main.lua:148: @programdir/modules/async/runjobs.lua:325: @programdir/modules/private/action/build/object.lua:100: @programdir/modules/core/tools/gcc.lua:980: main.cpp:1:1: error: ‘import’ does not name a type
    1 | import std;
      | ^~~~~~
main.cpp:1:1: note: C++20 ‘import’ only available with ‘-fmodules’, which is not yet enabled with ‘-std=c++20’
main.cpp: In function ‘int main()’:
main.cpp:4:8: error: ‘cout’ is not a member of ‘std’
    4 |   std::cout << std::format("Hello world! {}", 2024) << std::endl;
      |        ^~~~
main.cpp:1:1: note: ‘std::cout’ is defined in header ‘<iostream>’; this is probably fixable by adding ‘#include <iostream>’
  +++ |+#include <iostream>
    1 | import std;
main.cpp:4:21: error: ‘format’ is not a member of ‘std’
    4 |   std::cout << std::format("Hello world! {}", 2024) << std::endl;
      |                     ^~~~~~
main.cpp:1:1: note: ‘std::format’ is defined in header ‘<format>’; this is probably fixable by adding ‘#include <format>’
  +++ |+#include <format>
    1 | import std;
main.cpp:4:61: error: ‘endl’ is not a member of ‘std’
    4 |   std::cout << std::format("Hello world! {}", 2024) << std::endl;
      |                                                             ^~~~
main.cpp:1:1: note: ‘std::endl’ is defined in header ‘<ostream>’; this is probably fixable by adding ‘#include <ostream>’
  +++ |+#include <ostream>
    1 | import std;
stack traceback:
    [C]: in function 'error'
    [@programdir/core/base/os.lua:1075]:
    [@programdir/modules/core/tools/gcc.lua:980]: in function 'catch'
    [@programdir/core/sandbox/modules/try.lua:123]: in function 'try'
    [@programdir/modules/core/tools/gcc.lua:924]:
    [C]: in function 'xpcall'
    [@programdir/core/base/utils.lua:246]:
    [@programdir/core/tool/compiler.lua:288]: in function 'compile'
    [@programdir/modules/private/action/build/object.lua:100]: in function 'script'
    [@programdir/modules/private/action/build/object.lua:131]: in function 'build_object'
    [@programdir/modules/private/action/build/object.lua:156]: in function 'jobfunc'
    [@programdir/modules/async/runjobs.lua:241]:
    [C]: in function 'xpcall'
    [@programdir/core/base/utils.lua:246]: in function 'trycall'
    [@programdir/core/sandbox/modules/try.lua:117]: in function 'try'
    [@programdir/modules/async/runjobs.lua:224]: in function 'cotask'
    [@programdir/core/base/scheduler.lua:406]:

stack traceback:
	[C]: in function 'error'
	@programdir/core/base/os.lua:1075: in function 'base/os.raiselevel'
	(...tail calls...)
	@programdir/core/main.lua:329: in upvalue 'cotask'
	@programdir/core/base/scheduler.lua:406: in function <@programdir/core/base/scheduler.lua:399>

``

**Comment by star-hengxing** [comment]
`set_policy("build.c++.modules", true)`

**Comment by DawnMagnet** [comment]
> `set_policy("build.c++.modules", true)`

with some other error
```text
checking for gcc ... /usr/bin/gcc
checkinfo: cannot runv(nim --version), No such file or directory
checking for nim ... no
checkinfo: cannot runv(nim --version), No such file or directory
checking for nim ... no
checking for gcc ... /usr/bin/gcc
checking for the c++ compiler (cxx) ... gcc
checking for /usr/bin/gcc ... ok
checking for flags (-fPIC) ... ok
> gcc "-fPIC" "-m64"
checking for /usr/bin/gcc ... ok
checking for flags (gcc_modules) ... ok
> gcc "-fmodules" "-m64"
checking for flags (gcc_deps_format) ... ok
> gcc "-fdeps-format=p1689r5" "-m64"
checkinfo: @programdir/core/sandbox/modules/os.lua:273: cc1plus: error: to generate dependencies you must specify either ‘-M’ or ‘-MM’

stack traceback:
[C]: in function 'error'
[@programdir/core/base/os.lua:1075]:
[@programdir/core/sandbox/modules/os.lua:273]: in function 'runv'
[@programdir/modules/core/tools/gcc/has_flags.lua:42]:
checking for flags (gcc_deps_file) ... ok
> gcc "-fdeps-file=/tmp/.xmake1000/250502/_346F0FED18D348308171A74B362DDE30" "-m64"
checkinfo: @programdir/core/sandbox/modules/os.lua:273: cc1plus: error: to generate dependencies you must specify either ‘-M’ or ‘-MM’

stack traceback:
[C]: in function 'error'
[@programdir/core/base/os.lua:1075]:
[@programdir/core/sandbox/modules/os.lua:273]: in function 'runv'
[@programdir/modules/core/tools/gcc/has_flags.lua:42]:
checking for flags (gcc_deps_output) ... ok
> gcc "-fdeps-target=/tmp/.xmake1000/250502/_7C76F692935D420089B13BF891616C30.o" "-m64"
checkinfo: @programdir/core/sandbox/modules/os.lua:273: cc1plus: error: to generate dependencies you must specify either ‘-M’ or ‘-MM’

stack traceback:
[C]: in function 'error'
[@programdir/core/base/os.lua:1075]:
[@programdir/core/sandbox/modules/os.lua:273]: in function 'runv'
[@programdir/modules/core/tools/gcc/has_flags.lua:42]:
checking for flags (-std=c++23) ... ok
> gcc "-std=c++23" "-m64"
checking for flags (-D_GLIBCXX_USE_CXX11_ABI=0) ... ok
> gcc "-D_GLIBCXX_USE_CXX11_ABI=0" "-m64"
[  0%]: <main> generating.module.deps main.cpp
/usr/bin/gcc -m64 -std=c++23 -Ibuild/.gens/main/linux/x86_64/release/platform/windows/idl -fmodules -D_GLIBCXX_USE_CXX11_ABI=0 -E -x c++ main.cpp -MT build/.gens/main/linux/x86_64/release/rules/bmi/cache/modules/2e1fd567/main.cpp.json -MD -MF build/.gens/main/linux/x86_64/release/rules/bmi/cache/modules/2e1fd567/main.cpp.d -fdeps-format=p1689r5 -fdeps-file=build/.gens/main/linux/x86_64/release/rules/bmi/cache/modules/2e1fd567/main.cpp.json -fdeps-target=build/.objs/main/linux/x86_64/release/main.cpp.o -o build/.gens/main/linux/x86_64/release/rules/bmi/cache/modules/2e1fd567/main.cpp.i
[  0%]: <main> generating.module.deps /usr/lib/gcc/x86_64-pc-linux-gnu/15.1.1/../../../../lib/../include/c++/15.1.1/bits/std.cc
/usr/bin/gcc -m64 -std=c++23 -Ibuild/.gens/main/linux/x86_64/release/platform/windows/idl -fmodules -D_GLIBCXX_USE_CXX11_ABI=0 -E -x c++ /usr/lib/gcc/x86_64-pc-linux-gnu/15.1.1/../../../../lib/../include/c++/15.1.1/bits/std.cc -MT build/.gens/main/linux/x86_64/release/rules/bmi/cache/modules/694245f7/std.cc.json -MD -MF build/.gens/main/linux/x86_64/release/rules/bmi/cache/modules/694245f7/std.cc.d -fdeps-format=p1689r5 -fdeps-file=build/.gens/main/linux/x86_64/release/rules/bmi/cache/modules/694245f7/std.cc.json -fdeps-target=build/.objs/main/linux/x86_64/release/usr/lib/gcc/x86_64-pc-linux-gnu/15.1.1/__/__/__/__/lib/__/include/c++/15.1.1/bits/std.cc.o -o build/.gens/main/linux/x86_64/release/rules/bmi/cache/modules/694245f7/std.cc.i
[  0%]: <main> generating.module.deps /usr/lib/gcc/x86_64-pc-linux-gnu/15.1.1/../../../../lib/../include/c++/15.1.1/bits/std.compat.cc
/usr/bin/gcc -m64 -std=c++23 -Ibuild/.gens/main/linux/x86_64/release/platform/windows/idl -fmodules -D_GLIBCXX_USE_CXX11_ABI=0 -E -x c++ /usr/lib/gcc/x86_64-pc-linux-gnu/15.1.1/../../../../lib/../include/c++/15.1.1/bits/std.compat.cc -MT build/.gens/main/linux/x86_64/release/rules/bmi/cache/modules/694245f7/std.compat.cc.json -MD -MF build/.gens/main/linux/x86_64/release/rules/bmi/cache/modules/694245f7/std.compat.cc.d -fdeps-format=p1689r5 -fdeps-file=build/.gens/main/linux/x86_64/release/rules/bmi/cache/modules/694245f7/std.compat.cc.json -fdeps-target=build/.objs/main/linux/x86_64/release/usr/lib/gcc/x86_64-pc-linux-gnu/15.1.1/__/__/__/__/lib/__/include/c++/15.1.1/bits/std.compat.cc.o -o build/.gens/main/linux/x86_64/release/rules/bmi/cache/modules/694245f7/std.compat.cc.i
checking for flags (gcc_module_mapper) ... ok
> gcc "-fmodule-mapper=/tmp/.xmake1000/250502/_5EF8BBB806824E308899DFB6AA249E40" "-m64"
[ 42%]: <main> compiling.module.release std
mapper file --------
root /home/sgct/Example/CppExample
std build/.gens/main/linux/x86_64/release/rules/bmi/cache/modules/2e1fd567/std.gcm
--------
/usr/bin/gcc -c -m64 -std=c++23 -Ibuild/.gens/main/linux/x86_64/release/platform/windows/idl -fmodules -D_GLIBCXX_USE_CXX11_ABI=0 -fmodule-mapper=/tmp/.xmake1000/250502/main/usr/lib/gcc/x86_64-pc-linux-gnu/15.1.1/../../../../lib/../include/c++/15.1.1/bits/std.cc -x c++ -o build/.objs/main/linux/x86_64/release/usr/lib/gcc/x86_64-pc-linux-gnu/15.1.1/__/__/__/__/lib/__/include/c++/15.1.1/bits/std.cc.o /usr/lib/gcc/x86_64-pc-linux-gnu/15.1.1/../../../../lib/../include/c++/15.1.1/bits/std.cc
checking for flags (-fdiagnostics-color=always) ... ok
> gcc "-fdiagnostics-color=always" "-m64"
error: @programdir/core/main.lua:329: @programdir/actions/build/main.lua:148: @programdir/modules/async/runjobs.lua:325: ...ramdir/rules/c++/modules/modules_support/gcc/builder.lua:64: @programdir/modules/core/tools/gcc.lua:980: /usr/lib/gcc/x86_64-pc-linux-gnu/15.1.1/../../../../lib/../include/c++/15.1.1/bits/std.cc:1569:14: error: ‘basic_osyncstream’ has not been declared in ‘std’
1569 |   using std::basic_osyncstream;
|              ^~~~~~~~~~~~~~~~~
/usr/lib/gcc/x86_64-pc-linux-gnu/15.1.1/../../../../lib/../include/c++/15.1.1/bits/std.cc:1570:14: error: ‘basic_syncbuf’ has not been declared in ‘std’
1570 |   using std::basic_syncbuf;
|              ^~~~~~~~~~~~~
/usr/lib/gcc/x86_64-pc-linux-gnu/15.1.1/../../../../lib/../include/c++/15.1.1/bits/std.cc:1573:14: error: ‘osyncstream’ has not been declared in ‘std’
1573 |   using std::osyncstream;
|              ^~~~~~~~~~~
/usr/lib/gcc/x86_64-pc-linux-gnu/15.1.1/../../../../lib/../include/c++/15.1.1/bits/std.cc:1574:14: error: ‘syncbuf’ has not been declared in ‘std’
1574 |   using std::syncbuf;
|              ^~~~~~~
/usr/lib/gcc/x86_64-pc-linux-gnu/15.1.1/../../../../lib/../include/c++/15.1.1/bits/std.cc:1575:14: error: ‘wosyncstream’ has not been declared in ‘std’
1575 |   using std::wosyncstream;
|              ^~~~~~~~~~~~
/usr/lib/gcc/x86_64-pc-linux-gnu/15.1.1/../../../../lib/../include/c++/15.1.1/bits/std.cc:1576:14: error: ‘wsyncbuf’ has not been declared in ‘std’
1576 |   using std::wsyncbuf;
|              ^~~~~~~~
/usr/lib/gcc/x86_64-pc-linux-gnu/15.1.1/../../../../lib/../include/c++/15.1.1/bits/std.cc:2101:14: error: ‘emit_on_flush’ has not been declared in ‘std’
2101 |   using std::emit_on_flush;
|              ^~~~~~~~~~~~~
/usr/lib/gcc/x86_64-pc-linux-gnu/15.1.1/../../../../lib/../include/c++/15.1.1/bits/std.cc:2102:14: error: ‘noemit_on_flush’ has not been declared in ‘std’
2102 |   using std::noemit_on_flush;
|              ^~~~~~~~~~~~~~~
/usr/lib/gcc/x86_64-pc-linux-gnu/15.1.1/../../../../lib/../include/c++/15.1.1/bits/std.cc:2103:14: error: ‘flush_emit’ has not been declared in ‘std’
2103 |   using std::flush_emit;
|              ^~~~~~~~~~
/usr/lib/gcc/x86_64-pc-linux-gnu/15.1.1/../../../../lib/../include/c++/15.1.1/bits/std.cc:2507:21: error: ‘cmatch’ has not been declared in ‘std::pmr’
2507 |     using std::pmr::cmatch;
|                     ^~~~~~
/usr/lib/gcc/x86_64-pc-linux-gnu/15.1.1/../../../../lib/../include/c++/15.1.1/bits/std.cc:2508:21: error: ‘match_results’ has not been declared in ‘std::pmr’
2508 |     using std::pmr::match_results;
|                     ^~~~~~~~~~~~~
/usr/lib/gcc/x86_64-pc-linux-gnu/15.1.1/../../../../lib/../include/c++/15.1.1/bits/std.cc:2509:21: error: ‘smatch’ has not been declared in ‘std::pmr’
2509 |     using std::pmr::smatch;
|                     ^~~~~~
/usr/lib/gcc/x86_64-pc-linux-gnu/15.1.1/../../../../lib/../include/c++/15.1.1/bits/std.cc:2510:21: error: ‘wcmatch’ has not been declared in ‘std::pmr’
2510 |     using std::pmr::wcmatch;
|                     ^~~~~~~
/usr/lib/gcc/x86_64-pc-linux-gnu/15.1.1/../../../../lib/../include/c++/15.1.1/bits/std.cc:2511:21: error: ‘wsmatch’ has not been declared in ‘std::pmr’
2511 |     using std::pmr::wsmatch;
|                     ^~~~~~~
/usr/lib/gcc/x86_64-pc-linux-gnu/15.1.1/../../../../lib/../include/c++/15.1.1/bits/std.cc:2737:21: error: ‘basic_string’ has not been declared in ‘std::pmr’
2737 |     using std::pmr::basic_string;
|                     ^~~~~~~~~~~~
/usr/lib/gcc/x86_64-pc-linux-gnu/15.1.1/../../../../lib/../include/c++/15.1.1/bits/std.cc:2738:21: error: ‘string’ has not been declared in ‘std::pmr’
2738 |     using std::pmr::string;
|                     ^~~~~~
/usr/lib/gcc/x86_64-pc-linux-gnu/15.1.1/../../../../lib/../include/c++/15.1.1/bits/std.cc:2739:21: error: ‘u16string’ has not been declared in ‘std::pmr’
2739 |     using std::pmr::u16string;
|                     ^~~~~~~~~
/usr/lib/gcc/x86_64-pc-linux-gnu/15.1.1/../../../../lib/../include/c++/15.1.1/bits/std.cc:2740:21: error: ‘u32string’ has not been declared in ‘std::pmr’
2740 |     using std::pmr::u32string;
|                     ^~~~~~~~~
/usr/lib/gcc/x86_64-pc-linux-gnu/15.1.1/../../../../lib/../include/c++/15.1.1/bits/std.cc:2741:21: error: ‘u8string’ has not been declared in ‘std::pmr’
2741 |     using std::pmr::u8string;
|                     ^~~~~~~~
/usr/lib/gcc/x86_64-pc-linux-gnu/15.1.1/../../../../lib/../include/c++/15.1.1/bits/std.cc:2742:21: error: ‘wstring’ has not been declared in ‘std::pmr’
2742 |     using std::pmr::wstring;
|                     ^~~~~~~
/usr/lib/gcc/x86_64-pc-linux-gnu/15.1.1/../../../../lib/../include/c++/15.1.1/bits/std.cc:2787:14: error: ‘basic_syncbuf’ has not been declared in ‘std’
2787 |   using std::basic_syncbuf;
|              ^~~~~~~~~~~~~
/usr/lib/gcc/x86_64-pc-linux-gnu/15.1.1/../../../../lib/../include/c++/15.1.1/bits/std.cc:2789:14: error: ‘basic_osyncstream’ has not been declared in ‘std’
2789 |   using std::basic_osyncstream;
|              ^~~~~~~~~~~~~~~~~
/usr/lib/gcc/x86_64-pc-linux-gnu/15.1.1/../../../../lib/../include/c++/15.1.1/bits/std.cc:2790:14: error: ‘osyncstream’ has not been declared in ‘std’
2790 |   using std::osyncstream;
|              ^~~~~~~~~~~
/usr/lib/gcc/x86_64-pc-linux-gnu/15.1.1/../../../../lib/../include/c++/15.1.1/bits/std.cc:2791:14: error: ‘syncbuf’ has not been declared in ‘std’
2791 |   using std::syncbuf;
|              ^~~~~~~
/usr/lib/gcc/x86_64-pc-linux-gnu/15.1.1/../../../../lib/../include/c++/15.1.1/bits/std.cc:2792:14: error: ‘wosyncstream’ has not been declared in ‘std’
2792 |   using std::wosyncstream;
|              ^~~~~~~~~~~~
/usr/lib/gcc/x86_64-pc-linux-gnu/15.1.1/../../../../lib/../include/c++/15.1.1/bits/std.cc:2793:14: error: ‘wsyncbuf’ has not been declared in ‘std’
2793 |   using std::wsyncbuf;
|              ^~~~~~~~
stack traceback:
[C]: in function 'error'
[@programdir/core/base/os.lua:1075]:
[@programdir/modules/core/tools/gcc.lua:980]: in function 'catch'
[@programdir/core/sandbox/modules/try.lua:123]: in function 'try'
[@programdir/modules/core/tools/gcc.lua:924]:
[C]: in function 'xpcall'
[@programdir/core/base/utils.lua:246]:
[@programdir/core/tool/compiler.lua:288]: in function 'compile'
[...ramdir/rules/c++/modules/modules_support/gcc/builder.lua:64]: in function '_compile'
[...ramdir/rules/c++/modules/modules_support/gcc/builder.lua:233]: in function 'jobfunc'
[@programdir/modules/async/runjobs.lua:241]:
[C]: in function 'xpcall'
[@programdir/core/base/utils.lua:246]: in function 'trycall'
[@programdir/core/sandbox/modules/try.lua:117]: in function 'try'
[@programdir/modules/async/runjobs.lua:224]: in function 'cotask'
[@programdir/core/base/scheduler.lua:406]:

stack traceback:
[C]: in function 'error'
@programdir/core/base/os.lua:1075: in function 'os.raiselevel'
(...tail calls...)
@programdir/core/main.lua:329: in upvalue 'cotask'
@programdir/core/base/scheduler.lua:406: in function <@programdir/core/base/scheduler.lua:399>
```

**Comment by DawnMagnet** [comment]
seems it generate the windows files but i'm on linux 
 `/usr/bin/gcc -m64 -std=c++26 -Ibuild/.gens/main/linux/x86_64/release/platform/windows/idl` - is that correct?

**Comment by waruqi** [comment]
> seems it includes the windows files but i'm on linux `/usr/bin/gcc -m64 -std=c++26 -Ibuild/.gens/main/linux/x86_64/release/platform/windows/idl` - is that correct?

you can try dev version, this is a known issue, it has been fixed.

**Comment by DawnMagnet** [comment]
when i change to dev branch , no more windows deps but still can't fild a lot of thing inside std
```text
checking for platform ... linux
checking for architecture ... x86_64
checking for gcc ... /usr/bin/gcc
checkinfo: cannot runv(nim --version), No such file or directory
checking for nim ... no
checkinfo: cannot runv(nim --version), No such file or directory
checking for nim ... no
checking for gcc ... /usr/bin/gcc
checking for the c++ compiler (cxx) ... gcc
checking for /usr/bin/gcc ... ok
checking for flags (-fPIC) ... ok
> gcc "-fPIC" "-m64"
checking for /usr/bin/gcc ... ok
checking for flags (gcc_modules) ... ok
> gcc "-fmodules" "-m64"
checking for flags (gcc_deps_format) ... ok
> gcc "-fdeps-format=p1689r5" "-m64"
checkinfo: @programdir/core/sandbox/modules/os.lua:273: cc1plus: error: to generate dependencies you must specify either ‘-M’ or ‘-MM’

stack traceback:
[C]: in function 'error'
[@programdir/core/base/os.lua:1075]:
[@programdir/core/sandbox/modules/os.lua:273]: in function 'runv'
[@programdir/modules/core/tools/gcc/has_flags.lua:42]:
checking for flags (gcc_deps_file) ... ok
> gcc "-fdeps-file=/tmp/.xmake1000/250502/_351F80E0228444108D268C7574CB5F10" "-m64"
checkinfo: @programdir/core/sandbox/modules/os.lua:273: cc1plus: error: to generate dependencies you must specify either ‘-M’ or ‘-MM’

stack traceback:
[C]: in function 'error'
[@programdir/core/base/os.lua:1075]:
[@programdir/core/sandbox/modules/os.lua:273]: in function 'runv'
[@programdir/modules/core/tools/gcc/has_flags.lua:42]:
checking for flags (gcc_deps_output) ... ok
> gcc "-fdeps-target=/tmp/.xmake1000/250502/_024DE9FE3BC140108C9B5CC5AAE45040.o" "-m64"
checkinfo: @programdir/core/sandbox/modules/os.lua:273: cc1plus: error: to generate dependencies you must specify either ‘-M’ or ‘-MM’

stack traceback:
[C]: in function 'error'
[@programdir/core/base/os.lua:1075]:
[@programdir/core/sandbox/modules/os.lua:273]: in function 'runv'
[@programdir/modules/core/tools/gcc/has_flags.lua:42]:
checking for flags (-std=c++26) ... ok
> gcc "-std=c++26" "-m64"
checking for flags (-D_GLIBCXX_USE_CXX11_ABI=0) ... ok
> gcc "-D_GLIBCXX_USE_CXX11_ABI=0" "-m64"
[  3%]: <main> generating.module.deps main.cpp
/usr/bin/gcc -m64 -std=c++26 -fmodules -D_GLIBCXX_USE_CXX11_ABI=0 -E -x c++ main.cpp -MT build/.gens/main/linux/x86_64/release/rules/bmi/cache/modules/2e1fd567/main.cpp.json -MD -MF build/.gens/main/linux/x86_64/release/rules/bmi/cache/modules/2e1fd567/main.cpp.d -fdeps-format=p1689r5 -fdeps-file=build/.gens/main/linux/x86_64/release/rules/bmi/cache/modules/2e1fd567/main.cpp.json -fdeps-target=build/.objs/main/linux/x86_64/release/main.cpp.o -o build/.gens/main/linux/x86_64/release/rules/bmi/cache/modules/2e1fd567/main.cpp.i
[  3%]: <main> generating.module.deps /usr/lib/gcc/x86_64-pc-linux-gnu/15.1.1/../../../../lib/../include/c++/15.1.1/bits/std.cc
/usr/bin/gcc -m64 -std=c++26 -fmodules -D_GLIBCXX_USE_CXX11_ABI=0 -E -x c++ /usr/lib/gcc/x86_64-pc-linux-gnu/15.1.1/../../../../lib/../include/c++/15.1.1/bits/std.cc -MT build/.gens/main/linux/x86_64/release/rules/bmi/cache/modules/694245f7/std.cc.json -MD -MF build/.gens/main/linux/x86_64/release/rules/bmi/cache/modules/694245f7/std.cc.d -fdeps-format=p1689r5 -fdeps-file=build/.gens/main/linux/x86_64/release/rules/bmi/cache/modules/694245f7/std.cc.json -fdeps-target=build/.objs/main/linux/x86_64/release/usr/lib/gcc/x86_64-pc-linux-gnu/15.1.1/__/__/__/__/lib/__/include/c++/15.1.1/bits/std.cc.o -o build/.gens/main/linux/x86_64/release/rules/bmi/cache/modules/694245f7/std.cc.i
[  3%]: <main> generating.module.deps /usr/lib/gcc/x86_64-pc-linux-gnu/15.1.1/../../../../lib/../include/c++/15.1.1/bits/std.compat.cc
/usr/bin/gcc -m64 -std=c++26 -fmodules -D_GLIBCXX_USE_CXX11_ABI=0 -E -x c++ /usr/lib/gcc/x86_64-pc-linux-gnu/15.1.1/../../../../lib/../include/c++/15.1.1/bits/std.compat.cc -MT build/.gens/main/linux/x86_64/release/rules/bmi/cache/modules/694245f7/std.compat.cc.json -MD -MF build/.gens/main/linux/x86_64/release/rules/bmi/cache/modules/694245f7/std.compat.cc.d -fdeps-format=p1689r5 -fdeps-file=build/.gens/main/linux/x86_64/release/rules/bmi/cache/modules/694245f7/std.compat.cc.json -fdeps-target=build/.objs/main/linux/x86_64/release/usr/lib/gcc/x86_64-pc-linux-gnu/15.1.1/__/__/__/__/lib/__/include/c++/15.1.1/bits/std.compat.cc.o -o build/.gens/main/linux/x86_64/release/rules/bmi/cache/modules/694245f7/std.compat.cc.i
checking for flags (gcc_module_mapper) ... ok
> gcc "-fmodule-mapper=/tmp/.xmake1000/250502/_7526EF2F4B2A453082DA4184381E0B60" "-m64"
[ 25%]: <main> compiling.module.release std
mapper file --------
root /home/sgct/Example/CppExample
std build/.gens/main/linux/x86_64/release/rules/bmi/cache/modules/2e1fd567/std.gcm
--------
/usr/bin/gcc -c -m64 -std=c++26 -fmodules -D_GLIBCXX_USE_CXX11_ABI=0 -fmodule-mapper=/tmp/.xmake1000/250502/main/usr/lib/gcc/x86_64-pc-linux-gnu/15.1.1/../../../../lib/../include/c++/15.1.1/bits/std.cc -x c++ -o build/.objs/main/linux/x86_64/release/usr/lib/gcc/x86_64-pc-linux-gnu/15.1.1/__/__/__/__/lib/__/include/c++/15.1.1/bits/std.cc.o /usr/lib/gcc/x86_64-pc-linux-gnu/15.1.1/../../../../lib/../include/c++/15.1.1/bits/std.cc
checking for flags (-fdiagnostics-color=always) ... ok
> gcc "-fdiagnostics-color=always" "-m64"
error: @programdir/core/main.lua:329: @programdir/actions/build/main.lua:146: @programdir/modules/async/runjobs.lua:331: @programdir/rules/c++/modules/gcc/../gcc/builder.lua:64: @programdir/modules/core/tools/gcc.lua:1020: /usr/lib/gcc/x86_64-pc-linux-gnu/15.1.1/../../../../lib/../include/c++/15.1.1/bits/std.cc:1569:14: error: ‘basic_osyncstream’ has not been declared in ‘std’
1569 |   using std::basic_osyncstream;
|              ^~~~~~~~~~~~~~~~~
/usr/lib/gcc/x86_64-pc-linux-gnu/15.1.1/../../../../lib/../include/c++/15.1.1/bits/std.cc:1570:14: error: ‘basic_syncbuf’ has not been declared in ‘std’
1570 |   using std::basic_syncbuf;
|              ^~~~~~~~~~~~~
/usr/lib/gcc/x86_64-pc-linux-gnu/15.1.1/../../../../lib/../include/c++/15.1.1/bits/std.cc:1573:14: error: ‘osyncstream’ has not been declared in ‘std’
1573 |   using std::osyncstream;
|              ^~~~~~~~~~~
/usr/lib/gcc/x86_64-pc-linux-gnu/15.1.1/../../../../lib/../include/c++/15.1.1/bits/std.cc:1574:14: error: ‘syncbuf’ has not been declared in ‘std’
1574 |   using std::syncbuf;
|              ^~~~~~~
/usr/lib/gcc/x86_64-pc-linux-gnu/15.1.1/../../../../lib/../include/c++/15.1.1/bits/std.cc:1575:14: error: ‘wosyncstream’ has not been declared in ‘std’
1575 |   using std::wosyncstream;
|              ^~~~~~~~~~~~
/usr/lib/gcc/x86_64-pc-linux-gnu/15.1.1/../../../../lib/../include/c++/15.1.1/bits/std.cc:1576:14: error: ‘wsyncbuf’ has not been declared in ‘std’
1576 |   using std::wsyncbuf;
|              ^~~~~~~~
/usr/lib/gcc/x86_64-pc-linux-gnu/15.1.1/../../../../lib/../include/c++/15.1.1/bits/std.cc:2101:14: error: ‘emit_on_flush’ has not been declared in ‘std’
2101 |   using std::emit_on_flush;
|              ^~~~~~~~~~~~~
/usr/lib/gcc/x86_64-pc-linux-gnu/15.1.1/../../../../lib/../include/c++/15.1.1/bits/std.cc:2102:14: error: ‘noemit_on_flush’ has not been declared in ‘std’
2102 |   using std::noemit_on_flush;
|              ^~~~~~~~~~~~~~~
/usr/lib/gcc/x86_64-pc-linux-gnu/15.1.1/../../../../lib/../include/c++/15.1.1/bits/std.cc:2103:14: error: ‘flush_emit’ has not been declared in ‘std’
2103 |   using std::flush_emit;
|              ^~~~~~~~~~
/usr/lib/gcc/x86_64-pc-linux-gnu/15.1.1/../../../../lib/../include/c++/15.1.1/bits/std.cc:2507:21: error: ‘cmatch’ has not been declared in ‘std::pmr’
2507 |     using std::pmr::cmatch;
|                     ^~~~~~
/usr/lib/gcc/x86_64-pc-linux-gnu/15.1.1/../../../../lib/../include/c++/15.1.1/bits/std.cc:2508:21: error: ‘match_results’ has not been declared in ‘std::pmr’
2508 |     using std::pmr::match_results;
|                     ^~~~~~~~~~~~~
/usr/lib/gcc/x86_64-pc-linux-gnu/15.1.1/../../../../lib/../include/c++/15.1.1/bits/std.cc:2509:21: error: ‘smatch’ has not been declared in ‘std::pmr’
2509 |     using std::pmr::smatch;
|                     ^~~~~~
/usr/lib/gcc/x86_64-pc-linux-gnu/15.1.1/../../../../lib/../include/c++/15.1.1/bits/std.cc:2510:21: error: ‘wcmatch’ has not been declared in ‘std::pmr’
2510 |     using std::pmr::wcmatch;
|                     ^~~~~~~
/usr/lib/gcc/x86_64-pc-linux-gnu/15.1.1/../../../../lib/../include/c++/15.1.1/bits/std.cc:2511:21: error: ‘wsmatch’ has not been declared in ‘std::pmr’
2511 |     using std::pmr::wsmatch;
|                     ^~~~~~~
/usr/lib/gcc/x86_64-pc-linux-gnu/15.1.1/../../../../lib/../include/c++/15.1.1/bits/std.cc:2737:21: error: ‘basic_string’ has not been declared in ‘std::pmr’
2737 |     using std::pmr::basic_string;
|                     ^~~~~~~~~~~~
/usr/lib/gcc/x86_64-pc-linux-gnu/15.1.1/../../../../lib/../include/c++/15.1.1/bits/std.cc:2738:21: error: ‘string’ has not been declared in ‘std::pmr’
2738 |     using std::pmr::string;
|                     ^~~~~~
/usr/lib/gcc/x86_64-pc-linux-gnu/15.1.1/../../../../lib/../include/c++/15.1.1/bits/std.cc:2739:21: error: ‘u16string’ has not been declared in ‘std::pmr’
2739 |     using std::pmr::u16string;
|                     ^~~~~~~~~
/usr/lib/gcc/x86_64-pc-linux-gnu/15.1.1/../../../../lib/../include/c++/15.1.1/bits/std.cc:2740:21: error: ‘u32string’ has not been declared in ‘std::pmr’
2740 |     using std::pmr::u32string;
|                     ^~~~~~~~~
/usr/lib/gcc/x86_64-pc-linux-gnu/15.1.1/../../../../lib/../include/c++/15.1.1/bits/std.cc:2741:21: error: ‘u8string’ has not been declared in ‘std::pmr’
2741 |     using std::pmr::u8string;
|                     ^~~~~~~~
/usr/lib/gcc/x86_64-pc-linux-gnu/15.1.1/../../../../lib/../include/c++/15.1.1/bits/std.cc:2742:21: error: ‘wstring’ has not been declared in ‘std::pmr’
2742 |     using std::pmr::wstring;
|                     ^~~~~~~
/usr/lib/gcc/x86_64-pc-linux-gnu/15.1.1/../../../../lib/../include/c++/15.1.1/bits/std.cc:2787:14: error: ‘basic_syncbuf’ has not been declared in ‘std’
2787 |   using std::basic_syncbuf;
|              ^~~~~~~~~~~~~
/usr/lib/gcc/x86_64-pc-linux-gnu/15.1.1/../../../../lib/../include/c++/15.1.1/bits/std.cc:2789:14: error: ‘basic_osyncstream’ has not been declared in ‘std’
2789 |   using std::basic_osyncstream;
|              ^~~~~~~~~~~~~~~~~
/usr/lib/gcc/x86_64-pc-linux-gnu/15.1.1/../../../../lib/../include/c++/15.1.1/bits/std.cc:2790:14: error: ‘osyncstream’ has not been declared in ‘std’
2790 |   using std::osyncstream;
|              ^~~~~~~~~~~
/usr/lib/gcc/x86_64-pc-linux-gnu/15.1.1/../../../../lib/../include/c++/15.1.1/bits/std.cc:2791:14: error: ‘syncbuf’ has not been declared in ‘std’
2791 |   using std::syncbuf;
|              ^~~~~~~
/usr/lib/gcc/x86_64-pc-linux-gnu/15.1.1/../../../../lib/../include/c++/15.1.1/bits/std.cc:2792:14: error: ‘wosyncstream’ has not been declared in ‘std’
2792 |   using std::wosyncstream;
|              ^~~~~~~~~~~~
/usr/lib/gcc/x86_64-pc-linux-gnu/15.1.1/../../../../lib/../include/c++/15.1.1/bits/std.cc:2793:14: error: ‘wsyncbuf’ has not been declared in ‘std’
2793 |   using std::wsyncbuf;
|              ^~~~~~~~
stack traceback:
[C]: in function 'error'
[@programdir/core/base/os.lua:1075]:
[@programdir/modules/core/tools/gcc.lua:1020]: in function 'catch'
[@programdir/core/sandbox/modules/try.lua:123]: in function 'try'
[@programdir/modules/core/tools/gcc.lua:964]:
[C]: in function 'xpcall'
[@programdir/core/base/utils.lua:246]:
[@programdir/core/tool/compiler.lua:288]: in function 'compile'
[@programdir/rules/c++/modules/gcc/../gcc/builder.lua:64]: in function '_compile'
[@programdir/rules/c++/modules/gcc/../gcc/builder.lua:298]: in function 'jobfunc'
[@programdir/modules/async/runjobs.lua:247]:
[C]: in function 'xpcall'
[@programdir/core/base/utils.lua:246]: in function 'trycall'
[@programdir/core/sandbox/modules/try.lua:117]: in function 'try'
[@programdir/modules/async/runjobs.lua:230]: in function 'cotask'
[@programdir/core/base/scheduler.lua:406]:

stack traceback:
[C]: in function 'error'
@programdir/core/base/os.lua:1075: in function 'base/os.raiselevel'
(...tail calls...)
@programdir/core/main.lua:329: in upvalue 'cotask'
@programdir/core/base/scheduler.lua:406: in function <@programdir/core/base/scheduler.lua:399>

**Comment by star-hengxing** [comment]
`xmake f --policies=build.c++.gcc.modules.cxx11abi:true`

refer: https://zhuanlan.zhihu.com/p/15974278767 (chinese)

**Comment by Arthapz** [comment]
i will run some tests to check if this policies beeing disabled by default is still relevent

**Comment by DawnMagnet** [comment]
> `xmake f --policies=build.c++.gcc.modules.cxx11abi:true`
> 
> refer: https://zhuanlan.zhihu.com/p/15974278767 (chinese)

感谢，之前真没看到这篇，能否把这个内容加到xmake.io的文档里？

**Comment by DawnMagnet** [comment]
The final xmake.lua config is following and it works well(std>=20) with xmake dev branch(>=3.0.0)
```lua
set_languages("c++20")
target("main")
    set_kind("binary")
    set_policy("build.c++.modules", true)
    set_policy("build.c++.modules.gcc.cxx11abi", true)
    add_files("main.cpp")
```
