### ISSUE TITLE
linux compile go to windows binary :Checking for the Microsoft Visual Studio

### ISSUE THREAD

**Issue by czytcn** [xmake-io/xmake#908]
### Describe the bug
I run command on linux but it chek for vs?
```
➜  xmakeDemo xmake f -p windows -a x86_64 -m release
checking for the Microsoft Visual Studio (x86_64) version ... no
please run:
    - xmake config --vs=xxx [--vs_toolset=xxx]
or  - xmake global --vs=xxx
```

### Expected behavior
build windows binary success.

### Related Environment

- xmake version:3.6 latest dev
```
xmake v2.3.6+202007301004, A cross-platform build utility based on Lua
```
- os:Manjaro Linux
- target platform: Windows
- Go version: go 1.14.6

**Comment by waruqi** [comment]
I have fixed it, you can update to dev version and try it again.

```console
$ xmake update -s dev
$ xmake f -p windows -c
$ xmake
```

**Comment by czytcn** [comment]
> I have fixed it, you can update to dev version and try it again.
> 
> ```
> $ xmake update -s dev
> $ xmake f -p windows -c
> $ xmake
> ```

now I can compile.but still have some problem:

1. compile need root permition.
2.after build there was nothing in the build directory.
here is the log
```
➜  xmakeDemo  xmake f -p windows -a x86_64 -m release 
note: we need build go for windows_amd64 only once first! (pass -y or --confirm=y/n/d to skip confirm)?
please input: y (y/n)
y
building go for windows_amd64 .. error: go build cmd/dist: copying /tmp/go-build163553446/b001/exe/a.out: open cmd/dist/dist: permission denied

➜  xmakeDemo sudo xmake f -p windows -a x86          
➜  xmakeDemo ls
build  src  xmake.lua
➜  xmakeDemo cd build 
➜  build ls

```

**Comment by waruqi** [comment]
> building go for windows_amd64 .. error: go build cmd/dist: copying /tmp/go-build163553446/b001/exe/a.out: open cmd/dist/dist: permission denied

Because it will run the following command to build go for other platform.

```console
$ cd /usr/lib/go-1.6/src
$ GOOS=windows GOROOT_BOOTSTRAP=/usr/lib/go-1.6/ GOARCH=amd64 ./make.bash --no-clean
```

I have only tested cross-compilation on macos/windows before (see https://github.com/xmake-io/xmake/issues/898), but I haven’t tested it under linux. It seems that there are some permissions issues that need to be dealt with.

**Comment by waruqi** [comment]
I have fixed it, you can update the dev version and try it again. `xmake update -s dev`
